const backendDomain = process.env.REACT_APP_BACKEND_URL;
export const SummaryApi ={
    SignUP:{
        url:`${backendDomain}/api/v1/auth/signup`,
        method:'POST'
    },
    LOGIN:{
        url:`${backendDomain}/api/v1/auth/login`,
        method:'POST'
    },
    currentUser:{
        url:`${backendDomain}/api/v1/auth/user-details`,
        method:'GET'
    },
    logout:{
        url:`${backendDomain}/api/v1/auth/logout`,
        method:'GET'
    },
    allUsers:{
        url:`${backendDomain}/api/v1/auth/all-user`,
        method:'GET'
    },
    updateUsers:{
        url:`${backendDomain}/api/v1/auth/update-user-role`,
    },
  
    UploadPRoduct:{
        url:`${backendDomain}/api/v1/product/Upload-products`,
    },
    AllProducts:{
        url:`${backendDomain}/api/v1/product/All-products`,
    },
    UpdatePRoduct:{
        url:`${backendDomain}/api/v1/product/Update-products`,
    },
    GetProductByCategory:{
        url:`${backendDomain}/api/v1/product/Get-Category-Product`,
    },
    GethCategoryWiseProduct:{
        url:`${backendDomain}/api/v1/product/Get-Category-Wise-Product`,
    },
    ProductDetails:{
        url:`${backendDomain}/api/v1/product/product-details`,
    },
    AddToCart:{
        url:`${backendDomain}/api/v1/addToCart/Cart`,
    },
    CountAddTocartProduct:{
        url:`${backendDomain}/api/v1/addToCart/CountAddTocartProduct`,
    },
    AddToCartViewProduct:{
        url:`${backendDomain}/api/v1/addToCart/AddToCartViewProduct`,
    },
    UpdateAddToCart:{
        url:`${backendDomain}/api/v1/addToCart/UpdateAddToCart`,
          method:'POST'
    },
    DelAddToCart:{
        url:`${backendDomain}/api/v1/addToCart/DelAddToCart`,
        method:'POST'

    },
    SearchProduct:{
        url:`${backendDomain}/api/v1/product/SearchProduct`,
    },
    FiltterProduct:{
        url:`${backendDomain}/api/v1/product/FiltterProduct`,
    },
    checkout:{
        url:`${backendDomain}/api/v1/order/checkout`,
    },
    userOrders:{
        url:`${backendDomain}/api/v1/order/userOrders`,
    },
}